import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  markers,
  parseEntry,
  renderIndexBlock,
  spliceIndexBlock,
  isBlockCurrent,
  INDEX_STORES,
  INDEX_TARGETS,
  FIELD_SEP,
  type IndexRecord,
} from './index-contract.ts';

const SEP = FIELD_SEP;

const DECISION = `---
id: D-0007
status: active
recurrences:
  - gateway: S-003
  - worker: S-005
moot-when: the datastore client is removed
created: 2026-08-20
---

# timeout storms upstream of a datastore stay pool-shaped until saturation is excluded

## Decision
Trace pool saturation before upstream causes.
`;

const SHELL = [
  'Intro prose the skill author owns.',
  '',
  markers('decisions').begin,
  '- STALE line that should be overwritten',
  markers('decisions').end,
  '',
  'Trailing prose.',
  '',
].join('\n');

test('markers embed the store and are stable constants', () => {
  const m = markers('decisions');
  assert.equal(
    m.begin,
    '<!-- index:decisions begin — generated by tools/index-gen; do not edit between markers -->',
  );
  assert.equal(m.end, '<!-- index:decisions end -->');
});

test('parseEntry(decisions) reads id, status, and summary; never the payload', () => {
  const r = parseEntry('decisions', DECISION);
  assert.equal(r.id, 'D-0007');
  assert.equal(r.status, 'active');
  assert.equal(
    r['summary'],
    'timeout storms upstream of a datastore stay pool-shaped until saturation is excluded',
  );
  assert.ok(!JSON.stringify(r).includes('Trace pool saturation'));
});

test('parseEntry throws when id is absent — a draft is never indexed', () => {
  assert.throws(() => parseEntry('decisions', DECISION.replace('id: D-0007\n', '')));
});

test('renderIndexBlock(decisions) sorts by id and carries the superseded pointer', () => {
  const records: IndexRecord[] = [
    { id: 'D-0010', status: 'active', summary: 'later case', 'superseded-by': '' },
    { id: 'D-0003', status: 'superseded', summary: 'earlier case', 'superseded-by': 'D-0007' },
  ];
  assert.equal(
    renderIndexBlock('decisions', records),
    `- D-0003${SEP}superseded → D-0007${SEP}earlier case\n` +
      `- D-0010${SEP}active${SEP}later case\n`,
  );
});

test('renderIndexBlock(rules) leads with residue and (none)-fills an empty not-this', () => {
  const records: IndexRecord[] = [
    {
      id: 'R-0002',
      status: 'active',
      residue: 'presence only',
      'fires-when': 'diagnosing latency in a service with a datastore client',
      'not-this': '',
      floor: 'none',
    },
  ];
  assert.equal(
    renderIndexBlock('rules', records),
    `- R-0002${SEP}residue: presence only${SEP}` +
      `fires-when: diagnosing latency in a service with a datastore client${SEP}` +
      `not-this: (none)${SEP}floor: none${SEP}active\n`,
  );
});

test('renderIndexBlock(beliefs) keys on consult-when and flags postdictions', () => {
  const records: IndexRecord[] = [
    {
      id: 'B-0001',
      status: 'settled',
      'consult-when': 'estimating datastore burst capacity',
      deadline: '2026-08-01',
      postdiction: 'true',
      'superseded-by': '',
    },
  ];
  assert.equal(
    renderIndexBlock('beliefs', records),
    `- B-0001${SEP}consult-when: estimating datastore burst capacity${SEP}` +
      `deadline: 2026-08-01${SEP}settled${SEP}[postdiction]\n`,
  );
});

test('renderIndexBlock is empty for an empty store', () => {
  assert.equal(renderIndexBlock('decisions', []), '');
});

test('renderIndexBlock is deterministic across runs', () => {
  const records: IndexRecord[] = [
    { id: 'D-0002', status: 'active', summary: 'b', 'superseded-by': '' },
    { id: 'D-0001', status: 'active', summary: 'a', 'superseded-by': '' },
  ];
  assert.equal(renderIndexBlock('decisions', records), renderIndexBlock('decisions', records));
});

test('a field containing the delimiter is rejected, not silently corrupted', () => {
  const records: IndexRecord[] = [
    { id: 'D-0001', status: 'active', summary: `a${SEP}b`, 'superseded-by': '' },
  ];
  assert.throws(() => renderIndexBlock('decisions', records), /field separator/);
});

test('spliceIndexBlock replaces only the region between the markers', () => {
  const block = renderIndexBlock('decisions', [
    { id: 'D-0007', status: 'active', summary: 'a case', 'superseded-by': '' },
  ]);
  const out = spliceIndexBlock(SHELL, 'decisions', block);
  assert.ok(out.startsWith('Intro prose the skill author owns.'));
  assert.ok(out.includes('Trailing prose.'));
  assert.ok(!out.includes('STALE line'));
  assert.ok(out.includes(`- D-0007${SEP}active${SEP}a case`));
});

test('an empty store renders adjacent markers', () => {
  const out = spliceIndexBlock(SHELL, 'decisions', renderIndexBlock('decisions', []));
  const { begin, end } = markers('decisions');
  assert.ok(out.includes(`${begin}\n${end}`));
});

test('splice is idempotent and drives isBlockCurrent', () => {
  const records: IndexRecord[] = [
    { id: 'D-0007', status: 'active', summary: 'a case', 'superseded-by': '' },
  ];
  const once = spliceIndexBlock(SHELL, 'decisions', renderIndexBlock('decisions', records));
  assert.equal(isBlockCurrent(once, 'decisions', records), true);
  const twice = spliceIndexBlock(once, 'decisions', renderIndexBlock('decisions', records));
  assert.equal(twice, once);
});

test('a stale region is not current', () => {
  const records: IndexRecord[] = [
    { id: 'D-0007', status: 'active', summary: 'a case', 'superseded-by': '' },
  ];
  assert.equal(isBlockCurrent(SHELL, 'decisions', records), false);
});

test('missing markers are a hard failure, never a silent skip', () => {
  assert.throws(() => isBlockCurrent('no markers here', 'decisions', []), /markers missing/);
  assert.throws(() => spliceIndexBlock('no markers here', 'decisions', ''), /missing or malformed/);
});

test('every index target names a store and a skill path', () => {
  for (const store of INDEX_STORES) {
    assert.match(INDEX_TARGETS[store], /^skills\/.+\/SKILL\.md$/);
  }
});
