// The single source of truth for the store-index projection. Both index-gen
// (producer) and corpus-lint (verifier) import from here; neither reimplements
// parsing, rendering, or the markers. The governing spec is tools/INDEX-CONTRACT.md.
//
// This module is pure — string in, string out, no filesystem access. The
// drivers own file IO.

export type StoreId = 'decisions' | 'rules' | 'beliefs';

export const INDEX_STORES: readonly StoreId[] = ['decisions', 'rules', 'beliefs'];

// store -> the SKILL.md that hosts its generated region (repo-relative)
export const INDEX_TARGETS: Record<StoreId, string> = {
  decisions: 'skills/cases/SKILL.md',
  rules: 'skills/rules/SKILL.md',
  beliefs: 'skills/beliefs/SKILL.md',
};

// The one field delimiter. A value that contains it is rejected at render time
// rather than silently corrupting a line.
export const FIELD_SEP = ' · '; // ' · '

export interface IndexRecord {
  id: string;
  status: string;
  [field: string]: string;
}

export function markers(store: StoreId): { begin: string; end: string } {
  return {
    begin: `<!-- index:${store} begin — generated by tools/index-gen; do not edit between markers -->`,
    end: `<!-- index:${store} end -->`,
  };
}

// One entry file's text -> the record the index needs. Reads frontmatter and
// the title only; the payload sections never enter the record.
export function parseEntry(store: StoreId, fileText: string): IndexRecord {
  const fm = parseFrontmatter(fileText);
  const id = (fm['id'] ?? '').trim();
  if (id === '') {
    throw new Error(`parseEntry(${store}): entry has no 'id' in frontmatter`);
  }
  const status = (fm['status'] ?? '').trim();
  switch (store) {
    case 'decisions':
      return {
        id,
        status,
        summary: parseTitle(fileText),
        'superseded-by': fm['superseded-by'] ?? '',
      };
    case 'rules':
      return {
        id,
        status,
        residue: fm['residue'] ?? '',
        'fires-when': fm['fires-when'] ?? '',
        'not-this': fm['not-this'] ?? '',
        floor: fm['floor'] ?? '',
      };
    case 'beliefs':
      return {
        id,
        status,
        'consult-when': fm['consult-when'] ?? '',
        deadline: fm['deadline'] ?? '',
        postdiction: fm['postdiction'] ?? 'false',
        'superseded-by': fm['superseded-by'] ?? '',
      };
    default: {
      const unreachable: never = store;
      throw new Error(`parseEntry: unknown store ${String(unreachable)}`);
    }
  }
}

// Deterministic content BETWEEN the markers (no marker lines). Sorted by id
// ascending; each line LF-terminated; empty for an empty store.
export function renderIndexBlock(store: StoreId, records: IndexRecord[]): string {
  const sorted = [...records].sort((a, b) => idNum(a.id) - idNum(b.id));
  const lines = sorted.map((r) => renderLine(store, r));
  return lines.length === 0 ? '' : lines.map((line) => `${line}\n`).join('');
}

// Replace the region between a store's markers in a SKILL.md. Throws when the
// markers are absent or malformed — never a silent skip.
export function spliceIndexBlock(skillText: string, store: StoreId, block: string): string {
  const { begin, end } = markers(store);
  const beginIdx = skillText.indexOf(begin);
  const endIdx = skillText.indexOf(end);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    throw new Error(`spliceIndexBlock(${store}): markers missing or malformed in SKILL.md`);
  }
  const head = skillText.slice(0, beginIdx + begin.length);
  const tail = skillText.slice(endIdx);
  return `${head}\n${block}${tail}`;
}

// Is this SKILL.md's region already current for these records? Throws when the
// markers are absent.
export function isBlockCurrent(skillText: string, store: StoreId, records: IndexRecord[]): boolean {
  const { begin, end } = markers(store);
  if (!skillText.includes(begin) || !skillText.includes(end)) {
    throw new Error(`isBlockCurrent(${store}): markers missing in SKILL.md`);
  }
  return spliceIndexBlock(skillText, store, renderIndexBlock(store, records)) === skillText;
}

function renderLine(store: StoreId, r: IndexRecord): string {
  const id = r.id;
  const status = r.status;
  switch (store) {
    case 'decisions':
      return [
        `- ${id}`,
        `${status}${supersededArrow(status, r['superseded-by'])}`,
        field(id, 'summary', r['summary']),
      ].join(FIELD_SEP);
    case 'rules':
      return [
        `- ${id}`,
        `residue: ${field(id, 'residue', r['residue'])}`,
        `fires-when: ${field(id, 'fires-when', r['fires-when'])}`,
        `not-this: ${field(id, 'not-this', r['not-this'])}`,
        `floor: ${field(id, 'floor', r['floor'])}`,
        status,
      ].join(FIELD_SEP);
    case 'beliefs': {
      const postTag = isTrue(r['postdiction']) ? `${FIELD_SEP}[postdiction]` : '';
      return [
        `- ${id}`,
        `consult-when: ${field(id, 'consult-when', r['consult-when'])}`,
        `deadline: ${field(id, 'deadline', r['deadline'])}`,
        `${status}${postTag}${supersededArrow(status, r['superseded-by'])}`,
      ].join(FIELD_SEP);
    }
    default: {
      const unreachable: never = store;
      throw new Error(`renderLine: unknown store ${String(unreachable)}`);
    }
  }
}

function supersededArrow(status: string, supersededBy: string | undefined): string {
  const target = (supersededBy ?? '').trim();
  return status === 'superseded' && target !== '' ? ` → ${target}` : '';
}

function field(id: string, name: string, value: string | undefined): string {
  const trimmed = (value ?? '').trim();
  if (trimmed.includes(FIELD_SEP)) {
    throw new Error(`${id}: field '${name}' contains the field separator`);
  }
  return trimmed === '' ? '(none)' : trimmed;
}

function isTrue(value: string | undefined): boolean {
  return (value ?? '').trim().toLowerCase() === 'true';
}

function idNum(id: string): number {
  const m = /(\d+)\s*$/.exec(id);
  return m && m[1] ? Number.parseInt(m[1], 10) : 0;
}

// Top-level scalar keys of the YAML frontmatter block. Indented lines (list
// items, nested keys) are skipped — the index needs no array field.
function parseFrontmatter(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  const m = /^---\r?\n([\s\S]*?)\r?\n---/.exec(text);
  if (!m || !m[1]) return out;
  for (const line of m[1].split(/\r?\n/)) {
    const kv = /^([A-Za-z][\w-]*):\s?(.*)$/.exec(line);
    if (!kv || !kv[1]) continue;
    let value = (kv[2] ?? '').trim();
    if (
      value.length >= 2 &&
      ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'")))
    ) {
      value = value.slice(1, -1);
    }
    out[kv[1]] = value;
  }
  return out;
}

function parseTitle(text: string): string {
  const body = text.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/, '');
  const m = /^#\s+(.+?)\s*$/m.exec(body);
  return m && m[1] ? m[1].trim() : '';
}
